### PR TITLE
#10: Fails safely when a dependency's 'optional' value is not parseable to a 'bool'.

### PR DESCRIPTION
**Pull request by ododa**
Fails safely when a dependency's 'optional' value cannot be parsed to a 'bool'.
Adds a corresponding test case.

### CODE REVIEW

**Comment by bfabio** [comment]
@ododa Thanks for working on this! Let me know in case you need help.

**Comment by ododa** [comment]
Hi @bfabio . I just raised the PR. Could you have a look please?
One thing I didn't understand was the issue with phone numbers. Could you maybe provide a sample yaml with such a scenario?

**Review by bfabio — CHANGES_REQUESTED** [review]
The code looks good, let's follow the guidelines at https://github.com/italia/publiccode-parser-go/blob/master/testdata/README.md for the testcase (naming, making it minimal, remove comments unrelated to the issue tested, etc.)

**Comment by ododa** [comment]
Ciao @bfabio . I applied the changes following the testing guidelines. Could you please check again?

**Review by bfabio — APPROVED** [review]
Looks great, thanks @ododa :rocket:

**Pull request merged**
